### ISSUE TITLE
No responsiveness from SkypeBots

### ISSUE THREAD

**Issue by BroManDudeGuyPhD** [samczsun/Skype4J#101]
My code works If i send a message to myself from another Skype account, but not If a SkypeBot messages me.

**Comment by sponges** [comment]
Please send your code and Skype4J version. Try sending a message to yourself from skype web by logging into the bot account. If you can't do it, try adding and removing the contact.

**Comment by samczsun** [comment]
This will be worked on, but requires a somewhat major rewrite of the user API
