### ISSUE TITLE
API shut down

### ISSUE THREAD

**Issue by labotsky** [samczsun/Skype4J#107]
How I should use ErrorHandler to catch  that Api is shut down?
Can somebody show example code?

**Comment by samczsun** [comment]
https://samczsun.github.io/Skype4J/com/samczsun/skype4j/SkypeBuilder.html#withExceptionHandler-com.samczsun.skype4j.exceptions.handler.ErrorHandler-

https://samczsun.github.io/Skype4J/com/samczsun/skype4j/exceptions/handler/ErrorHandler.html#handle-com.samczsun.skype4j.exceptions.handler.ErrorSource-java.lang.Throwable-boolean-

If `shutdown` is true then the API will not be usable
