### ISSUE TITLE
Very slow login.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [samczsun/Skype4J#108]
I don't know if it is the API or if it is Skype, but after updating to 0.2.0 the login proccess takes A LOT. (more than 50 seconds to login!)

So, is this an API change or is the Skype API that is slow as fuck?

(I remember using another API before Skype4J that used the Web Skype API and it was also slow to login)

**Comment by ducc** [comment]
Accounts with lots of contacts, chats etc take a while to login. It's just a drawback of preloading resources. I find that this is not an issue on my dedicated server, only on my slow home internet.

**Comment by MrPowerGamerBR** [comment]
@sponges yeah, maybe it is because I have a lot of contacts...

Strange, the 0.1.6 version logs in quickly and loads all of my contacts (no, I didn't use skype.loadAllContacts()), but the 0.2.0 takes more than 1 minute to login and not all of my contacts are loaded.

**Comment by ducc** [comment]
I'll try it now, I haven't updated yet.

**Comment by MrPowerGamerBR** [comment]
@sponges I updated but I reverted to 0.1.6 because there was some bugs with the new version (I already created issues for the bugs I found ;) )

**Comment by samczsun** [comment]
In 0.2.0 Skype4J takes advantage of the new profiles API to load all the profile info of users in a chat when the chat is loaded. This also has the added benefit of not running into rate limit issues because of loading every user one by one

**Comment by MrPowerGamerBR** [comment]
@samczsun Oh, so that's why it takes a lot, it isn't a issue to me tho, I was just wondering if it was normal.

---

Also, a small question: It is really impossible to get the user status? Miranda-NG Skype plugin uses the Web Skype API and can get the users status.

![http://lori.mrpowergamerbr.com/sharex/Miranda64_2016-07-30_13-43-49.png](http://lori.mrpowergamerbr.com/sharex/Miranda64_2016-07-30_13-43-49.png)

And I'm not sure, but I think Skype4Pidgin also can get the user status and it does use the Web Skype API by subscribing to the contact, allowing to get status changes: https://github.com/EionRobb/skype4pidgin/blob/cabcc1befee74ed6d4bbdc1cb2bcd4263c837c0c/skypeweb/skypeweb_messages.c#L914

I think the URL is "https://client-s.gateway.messenger.live.com/v1/users/ME/contacts/", it is added in the Endpoints as "UNAUTHORIZE_CONTACT" but it is never used anywhere in the Skype4J.

EDIT: Now two questions for @samczsun (that I forgot to ask)

After updating to the 0.2.0 API, how can I get the contact with a Message? In 0.1.6 I can get the contact by using `e.getMessage().getSender().getContact()` but in 0.2.0 the method was changed and it seems I can't get the contact, only the "Participant".

Now the last question, there isn't a way to get all medias (not the image file, just something like "hey, this is a image that someone shared") shared in a chat, right?

**Comment by MrPowerGamerBR** [comment]
@samczsun I think this can help you implement Online Status for Contacts ;)

https://github.com/vemacs/jSkype/blob/master/src/main/java/xyz/gghost/jskype/internal/poller/OnlineStatusPoll.java

(I tried using jSkype before but it was buggy compared to Skype4J)

**Comment by samczsun** [comment]
It's not impossible to do it, I've just yet to implement it yet.

https://github.com/samczsun/Skype4J/blob/master/src/main/java/com/samczsun/skype4j/internal/EventType.java

User implements Participant, you can check `instanceof`

**Comment by MrPowerGamerBR** [comment]
@samczsun wow, didn't know about that, thanks :)

I will try updating to 0.2.0, will create another issue if I find one, I will also close this issue since the problem has been already solved (well, not really solved, but...)
