### ISSUE TITLE
Text format

### ISSUE THREAD

**Issue by SandroCoutinho** [samczsun/Skype4J#115]
I've tried using some text formats like bold and italic and it doesn't work.

Could this even be added?

![monosnap 2016-07-31 23-30-39](https://cloud.githubusercontent.com/assets/5498024/17279811/d32480e0-5776-11e6-918b-5f9f5d3d4804.png)

**Comment by samczsun** [comment]
What code are you using? I just tried it and it worked fine

**Comment by SandroCoutinho** [comment]
A simple sendMessage

`Utils.sendMessage(e.getChat(), "*Invalid command*");`

`public static void sendMessage(Chat chat, String message) {
        try {
            chat.sendMessage(message);
        } catch (ConnectionException e) {
            e.printStackTrace();
        }
    }`

**Comment by samczsun** [comment]
You'll want to use the Message API

**Comment by SandroCoutinho** [comment]
How about would I do that, been trying but can't, very sorry to disturb you.

**Comment by samczsun** [comment]
https://samczsun.github.io/Skype4J/com/samczsun/skype4j/formatting/Message.html#create--

Message.create().withText(Text.rich("Invalid Command").withBold());

**Comment by SandroCoutinho** [comment]
Thank you sir.
