### ISSUE TITLE
Get Group Chat Title

### ISSUE THREAD

**Issue by nicksellis102** [samczsun/Skype4J#116]
I've been looking for a couple days now and have been unable to find a way to get the GroupChat title.

**Comment by PrinzKenny1** [comment]
I have done it.. but the only Problem is that if you get the name and then change the name its shows the old name :/ Maybe its a bug. Here is the Code:

`GroupChat g = (GroupChat) e.getChat();`
`String groupname = g.getTopic();`

e is the MessageReceivedEvent ^^
I hope I can help you with this :)

**Comment by nicksellis102** [comment]
Thanks, it works. but as you said it doesn't change.

**Comment by nicksellis102** [comment]
@samczsun this can be closed
