### ISSUE TITLE
Skype Name Change

### ISSUE THREAD

**Issue by PrinzKenny1** [samczsun/Skype4J#119]
Hey, I ask me if you can add Skype Name Change Support? And yes you can edit the name in web. If you dont know how here is a link: https://login.skype.com/login
If you loggin there and go to "Edit Profile" and go again on "Edit Profile" you can change the name by put in "First Name" and "Last Name".

I really hope that you add it, because I`m code a Skype System for User Support and when it`s away or goes Online I want to show that the System is loading or something.

And thanks for this awesome API :smile: 

P.S. Sorry for my bad english I`m from Germany.

**Comment by ducc** [comment]
Just a note, Skype will not keep up with this. Synchronization between contacts as well as desktop & web clients will be inaccurate.
This has been done before with other APIs such as Skype4COM and has never worked properly.
