### ISSUE TITLE
Chat is null when message received

### ISSUE THREAD

**Issue by yar229** [samczsun/Skype4J#12]
ш■ы 22, 2015 1:39:15 PM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
SEVERE: Exception while handling message
java.lang.NullPointerException
        at com.samczsun.skype4j.internal.MessageType.getUser(MessageType.java:33
4)
        at com.samczsun.skype4j.internal.MessageType.access$200(MessageType.java
:32)
        at com.samczsun.skype4j.internal.MessageType$3.handle(MessageType.java:5
5)
        at com.samczsun.skype4j.internal.SkypeImpl$1$1.run(SkypeImpl.java:142)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:603)
        at java.lang.Thread.run(Thread.java:935)

ш■ы 22, 2015 1:39:15 PM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
SEVERE: {"eventMessages":[{"id":1008,"type":"EventMessage","resourceType":"NewMe
ssage","time":"2015-07-22T09:38:47Z","resourceLink":"https://bay-client-s.gatewa
y.messenger.live.com/v1/users/ME/conversations/19:c6a914c896a54ac1b0cb3040ea9124
88@thread.skype/messages/1437557927265","resource":{"clientmessageid":"107547954
58636289908","threadtopic":"SkypeWebText","messagetype":"RichText","originalarri
valtime":"2015-07-22T09:38:46.648Z","isactive":false,"from":"https://bay-client-
s.gateway.messenger.live.com/v1/users/ME/contacts/8:yarwork","id":"1437557927265
","conversationLink":"https://bay-client-s.gateway.messenger.live.com/v1/users/M
E/conversations/19:c6a914c896a54ac1b0cb3040ea912488@thread.skype","type":"Messag
e","imdisplayname":"YaR Rou","ackrequired":"https://bay-client-s.gateway.messeng
er.live.com/v1/users/ME/conversations/ALL/messages/1437557927265/ack","content":
"7","composetime":"2015-07-22T09:38:46.648Z"}}]}
ш■ы 22, 2015 1:39:15 PM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
SEVERE: {"eventMessages":[{"id":1010,"type":"EventMessage","resourceType":"NewMe
ssage","time":"2015-07-22T09:39:05Z","resourceLink":"https://bay-client-s.gatewa
y.messenger.live.com/v1/users/ME/conversations/19:c6a914c896a54ac1b0cb3040ea9124
88@thread.skype/messages/1437557945220","resource":{"clientmessageid":"161333209
8838435701","threadtopic":"SkypeWebText","messagetype":"RichText","originalarriv
altime":"2015-07-22T09:39:04.947Z","isactive":false,"from":"https://bay-client-s
.gateway.messenger.live.com/v1/users/ME/contacts/8:yarwork","id":"1437557945220"
,"conversationLink":"https://bay-client-s.gateway.messenger.live.com/v1/users/ME
/conversations/19:c6a914c896a54ac1b0cb3040ea912488@thread.skype","type":"Message
","imdisplayname":"YaR Rou","ackrequired":"https://bay-client-s.gateway.messenge
r.live.com/v1/users/ME/conversations/ALL/messages/1437557945220/ack","content":"
message text","composetime":"2015-07-22T09:39:04.947Z"}}]}

**Comment by samczsun** [comment]
Ah, my bad. Will be fixing promptly.

**Comment by yar229** [comment]
Maybe the same?

``` CSharp
Skype _skype = new SkypeImpl(Settings.Default.SkypeLogin, Settings.Default.SkypePassword);
_skype.login();
var dispatcherv = _skype.getEventDispatcher();
dispatcherv.registerListener(new MessageListener(OnSkypeMessage));
_skype.subscribe();
var chats = _skype.getAllChats().toArray();
```

chats is always empty...

P.S. not always, of course, ChatImpl.createChat put one into it, but how I can get list of all chats/contacts on account?

**Comment by FirKys** [comment]
```
июл 23, 2015 5:52:21 PM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
SEVERE: Exception while handling message
java.lang.NullPointerException
    at com.samczsun.skype4j.internal.MessageType.getUser(MessageType.java:331)
    at com.samczsun.skype4j.internal.MessageType.access$4(MessageType.java:328)
    at com.samczsun.skype4j.internal.MessageType$3.handle(MessageType.java:55)
    at com.samczsun.skype4j.internal.SkypeImpl$1$1.run(SkypeImpl.java:141)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

июл 23, 2015 5:52:21 PM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
SEVERE: {"eventMessages":[{"id":1016,"type":"EventMessage","resourceType":"NewMessage","time":"2015-07-23T14:52:23Z","resourceLink":"https://bay-client-s.gateway.messenger.live.com/v1/users/ME/conversations/19:11acc85822c0440787e89321db8e9a52@thread.skype/messages/1437663143744","resource":{"clientmessageid":"1437663153695","threadtopic":"Sky-Mine | Флудильня.","messagetype":"RichText","originalarrivaltime":"2015-07-23T14:52:23.710Z","contenttype":"text","isactive":true,"from":"https://bay-client-s.gateway.messenger.live.com/v1/users/ME/contacts/8:poison1x","id":"1437663143744","conversationLink":"https://bay-client-s.gateway.messenger.live.com/v1/users/ME/conversations/19:11acc85822c0440787e89321db8e9a52@thread.skype","type":"Message","imdisplayname":"poison1x","ackrequired":"https://bay-client-s.gateway.messenger.live.com/v1/users/ME/conversations/ALL/messages/1437663143744/ack","content":"List of available commands:   <i>!help</i>, <i>!score</i>, <i>!music</i>, <i>!spin</i>, <i>!online</i>, <i>!boobs</i>, <i>!say</i>","composetime":"2015-07-23T14:52:23.710Z"}}]}

```

+1

Good luck.
Waiting for update :3

**Comment by yar229** [comment]
You can just use SkypeImpl.getChat from previous commit till it not done ;)

**Comment by samczsun** [comment]
This bug is fixed, but the most recent commit is still experimental (note all the System.out.println calls). Using non-deployed builds is not recommended but if you want to I won't stop you.

**Comment by yar229** [comment]
Ok, that's a deal :)
Thanks for tha fix!

**Comment by sistem21** [comment]
i've the same error,every time that my bot sends a message,it print this stacktrace in console:
lug 30, 2015 1:43:25 PM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
GRAVE: Exception while handling message
java.lang.IllegalArgumentException: User must not be null
    at org.jsoup.helper.Validate.notNull(Validate.java:26)
    at com.samczsun.skype4j.internal.ChatMessageImpl.createMessage(ChatMessageImpl.java:14)
    at com.samczsun.skype4j.internal.MessageType$3.handle(MessageType.java:58)
    at com.samczsun.skype4j.internal.SkypeImpl$1$1.run(SkypeImpl.java:114)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

lug 30, 2015 1:43:25 PM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
GRAVE: {"eventMessages":[{"id":1007,"type":"EventMessage","resourceType":"NewMessage","time":"2015-07-30T11:43:18Z","resourceLink":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:napolissimo1926/messages/1438256598532","resource":{"clientmessageid":"1438256604955","messagetype":"RichText","originalarrivaltime":"2015-07-30T11:43:18.556Z","contenttype":"text","isactive":true,"from":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/contacts/8:siwabot","id":"1438256598532","conversationLink":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:napolissimo1926","type":"Message","imdisplayname":"siwabot","ackrequired":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/ALL/messages/1438256598532/ack","content":"<b>(napolissimo1926)</b>","composetime":"2015-07-30T11:43:18.556Z"}}]}
