### ISSUE TITLE
getMessage().getSendTime(); not working?

### ISSUE THREAD

**Issue by lbessant98** [samczsun/Skype4J#125]
`time = e.getMessage().getSentTime();`

Can't seem to get the time throught this method, instead it just produces a long value (in my case, 1472491228234).

Anybody else having the same problem or am I doing something stupidly wrong?

**Comment by ghost** [comment]
If I m not wrong this long is the time. In millisecond. Like a lot of person use it in computer science

**Comment by ex00** [comment]
Hello, you can convert millisecond to date.  [See this topic](http://stackoverflow.com/questions/8237193/how-to-convert-currenttimemillis-to-a-date-in-java)
