### ISSUE TITLE
Message encoding

### ISSUE THREAD

**Issue by yar229** [samczsun/Skype4J#13]
Message.getContent().asPlainText()
Message.getContent().asHtml()

returns message text in Windows-1251 encoding.
Is it right? Maybe UTF will be better?

**Comment by samczsun** [comment]
Message#asPlainText() and Message#asHtml() will return a String built from Strings you provided in Text.plain(*). If it is returning text encoded in Windows-1251, then you are passing it strings encoded in Windows-1251
