### ISSUE TITLE
Functionality for /set banlist, /get banlist

### ISSUE THREAD

**Issue by AnastasiaTamazlykar** [samczsun/Skype4J#130]
Please, advise how to know endpoints for these commands and type ,content whatever for such requests? Unfortunately, web version of skype is limited. 
Please, contact me, in case you can share experience of getting this info
tamazlikar@gmail.com

Thanks in advance, Anastasiia

**Comment by AnastasiaTamazlykar** [comment]
Found how, thanks

**Comment by ctian1** [comment]
How'd you do it?

**Comment by AnastasiaTamazlykar** [comment]
Set banlist (override previous value)

Endpoints.custom("https://client-s.gateway.messenger.live.com/v1/threads/<chat name>@thread.skype/properties?name=banneduserlist", (SkypeImpl) SkypeHelper.getSkype()).header("Authentication", "skypetoken=" + ((SkypeImpl) SkypeHelper.getSkype()).getSkypeToken()) 
 .expect(200, "") 
 .put(new JsonObject().add("banneduserlist","8:<user id>"));

**Comment by AnastasiaTamazlykar** [comment]
Set banlist (override previous value)

Endpoints.custom("https://client-s.gateway.messenger.live.com/v1/threads/{chat id}@thread.skype/properties?name=banneduserlist", (SkypeImpl) SkypeHelper.getSkype()).header("Authentication", "skypetoken=" + ((SkypeImpl) SkypeHelper.getSkype()).getSkypeToken()) 
.expect(200, "") 
.put(new JsonObject().add("banneduserlist","8:{user id}"));
