### ISSUE TITLE
Feature/Question/Help

### ISSUE THREAD

**Issue by MadProgrammerGR** [samczsun/Skype4J#147]
hello, i have been using this to make a simple bot game that asks simple questions yes/no etc..

I have problem with chat id, i just dont know how to get it, is there any way to use join link instead like: (https://join.skype.com/xxxxxx) to connect to a chat? or else how can i get the chat id?
Thanks!

**Comment by AnonymousDr** [comment]
Write /get name on the group.

Regards.

**Comment by MadProgrammerGR** [comment]
Thanks man! &#128077;
