### ISSUE TITLE
Group chat

### ISSUE THREAD

**Issue by eehhaa** [samczsun/Skype4J#149]
How can I send and check for messages inside of group chats? I am currently using `Message.sendMessage(e.getChat, "Message");` how can I make it send to groups as right now it only works in private chat.

**Comment by gw2princeps** [comment]
Check if your chat is a instanceof GroupChat. Then it should work

**Comment by eehhaa** [comment]
Still doesn't work instead it says that I have to specify a group chat and can't do `e.getChat();`

**Comment by gw2princeps** [comment]
check out my implementation https://github.com/SpatiumPrinceps/PrincepsLib/blob/master/src/main/java/biz/princeps/lib/broadcasting/PSkype.java
just ignore the bukkit stuff, its just for running interaction with Skype on another thread. 
not sure if it helps you...
