### ISSUE TITLE
Send an invite to friends and message

### ISSUE THREAD

**Issue by FirKys** [samczsun/Skype4J#15]
Hello :) How i cant:
- send invite in friends list if i know only login skype?
- send message if i know only login skype?

i try. But  didn't work

```
bot.getSkype().loadChat("8:firkys").sendMessage(Message.fromHtml("test"));
```

**Comment by ducc** [comment]
Please elaborate on "didn't work".
Try using getChat instead of loadChat,

**Comment by ducc** [comment]
Also read this regarding sending/accepting contacts https://github.com/samczsun/Skype4J/issues/5

**Comment by samczsun** [comment]
Actions involving contact requests are not supported at this moment
