### ISSUE TITLE
Message text parsing exception

### ISSUE THREAD

**Issue by yar229** [samczsun/Skype4J#18]
...and there is no Message.fromPlainText...

``` java
Message.fromHtml("zzz <ss😠R)</ss> zzz (don't ask me what the hell this text is)");
```

java.util.EmptyStackException

   at java.util.Stack.peek()
   at com.samczsun.skype4j.formatting.Message$1.head(Node , Int32 )
   at org.jsoup.select.NodeTraversor.traverse(Node root)
   at org.jsoup.nodes.Node.traverse(NodeVisitor nodeVisitor)
   at com.samczsun.skype4j.formatting.Message.fromHtml(String text)

**Comment by ducc** [comment]
For plain text, you can use
`Message.create().with(Text.plain("my plain text"));`

(I'm assuming that the issue here is that you can't send < or >)

**Comment by yar229** [comment]
Thanks!

**Comment by ducc** [comment]
I just added a wiki page on formatting [here](https://github.com/samczsun/Skype4J/wiki/Messages) if you need some help with the formatting system.

**Comment by yar229** [comment]
hm

So if I need to send '<'

```
msg = Message.fromHtml("<"); c.sendMessage(msg);  // --> Exception!
msg = Message.create().with(Text.plain("<")); c.sendMessage(msg);   // --> Exception!

msg = Message.fromHtml("&lt;"); c.sendMessage(msg);  // --> Exception!
msg = Message.create().with(Text.plain("&lt;")); c.sendMessage(msg);   // ok

msg = Message.fromHtml("&#60;"); c.sendMessage(msg);  // --> Exception!
msg = Message.create().with(Text.plain("&#60;")); c.sendMessage(msg);   // ok
```

So whats the right way?

P.S. And if i need to send `"<b>&lt;</b>"` or `"<b>&#60;</b>"` and want to receive "<"?

**Comment by ducc** [comment]
@samczsun shouldn't it send < & > fine in plain text?

For now, you can use Unicode characters.
To send <, you would use \u003C.

I would suggest using [this site](http://www.fileformat.info/info/unicode/char/search.htm) for finding the Unicode characters.
![Unicode site](http://i.imgur.com/kMLsPhJ.png)
Inside the black squares is your unicode characters. To use them, just put them in the format of `\uXXXX`.
