### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by AN2548** [samczsun/Skype4J#29]
I've been using the maven 0.0.8-snapshot, for the last couple of days, but, seeing as Samczsun implemented a whole load of new features and events, I decided to compile the github version of the project, however, in this new version, I can't login, since there is no skype.login(username,password) input. I'd really like to start using all the new features, especially the events, so could someone tell me how to login?

**Comment by yar229** [comment]
that's in C#, but no matter

``` CSharp
var skypeBuilder = new SkypeBuilder(_user, _password).withAllResources();
var skype = skypeBuilder.build();

skype.login();
skype.getEventDispatcher().registerListener(new SkypeWebListener(_webListener, this));
skype.subscribe();
```

**Comment by AN2548** [comment]
Thanks. What's in C#?

EDIT >> Your response is in C#, right?

**Comment by yar229** [comment]
Yep

**Comment by AN2548** [comment]
Okay, that worked. Thanks, for the help :+1:  :PPPPPPPPPPPPP

**Comment by SevakAvet** [comment]
What if Skype class doesn't have login method?

**Comment by ducc** [comment]
Either you've messed up your maven config, or you're trying to use the new versions that aren't on maven.

Use 0.08-SNAPSHOT for best results :)
