### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by yar229** [samczsun/Skype4J#31]
After about two weeks of using this lib exception thrown every time I try to login

com.samczsun.skype4j.exceptions.InvalidCredentialsException: Signing in failed. Please double-check your Skype Name and re-enter your password.

web.skype.com in browser on this machine is working ok...

**Comment by ducc** [comment]
Login to browser a few times, wait a few hours. Probably a rate limiting issue or security checks.
This also happens sometimes when you have lots of people logged into one account.

tl;dr wait a day or two.
