### ISSUE TITLE
User is always null

### ISSUE THREAD

**Issue by sistem21** [samczsun/Skype4J#33]
Hi,i've a problem..when anyone sends a message to my bot,and my bot answer,i receive this error:

set 17, 2015 10:18:48 AM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
GRAVE: Exception while handling message
java.lang.IllegalArgumentException: User must not be null
    at org.jsoup.helper.Validate.notNull(Validate.java:26)
    at com.samczsun.skype4j.internal.ChatMessageImpl.createMessage(ChatMessageImpl.java:14)
    at com.samczsun.skype4j.internal.MessageType$3.handle(MessageType.java:58)
    at com.samczsun.skype4j.internal.SkypeImpl$1$1.run(SkypeImpl.java:114)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

set 17, 2015 10:18:48 AM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
GRAVE: {"eventMessages":[{"id":1004,"type":"EventMessage","resourceType":"NewMessage","time":"2015-09-17T08:18:38Z","resourceLink":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:napolissimo1926/messages/1442477918079","resource":{"clientmessageid":"1442477927523","messagetype":"RichText","originalarrivaltime":"2015-09-17T08:18:38.314Z","contenttype":"text","isactive":true,"from":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/contacts/8:siwabot","id":"1442477918079","conversationLink":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:napolissimo1926","type":"Message","imdisplayname":"siwabot","ackrequired":"https://db3-client-s.gateway.messenger.live.com/v1/users/ME/conversations/ALL/messages/1442477918079/ack","content":"Debug","composetime":"2015-09-17T08:18:38.314Z"}}]}

Then I get every minute this message:
set 17, 2015 10:46:50 AM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
GRAVE: Exception while handling message
java.lang.NullPointerException
    at com.samczsun.skype4j.internal.SkypeImpl$1$1.run(SkypeImpl.java:106)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

set 17, 2015 10:46:50 AM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
GRAVE: {}

**Comment by sistem21** [comment]
You close this but you don't help me?

**Comment by ducc** [comment]
Because you didn't provide anything for us to help with.

**Comment by samczsun** [comment]
I closed it because the first issue I've already given you the solution for, and the second has already been fixed

**Comment by sistem21** [comment]
it is just 1 problem,when did you give me the solution?however here is the code:

``` java
package me.sistem21.SiwaBot;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;

import com.samczsun.skype4j.Skype;
import com.samczsun.skype4j.chat.Chat;
import com.samczsun.skype4j.events.EventHandler;
import com.samczsun.skype4j.events.Listener;
import com.samczsun.skype4j.events.chat.message.MessageReceivedEvent;
import com.samczsun.skype4j.exceptions.SkypeException;
import com.samczsun.skype4j.formatting.Message;
import com.samczsun.skype4j.formatting.Text;

public class Main{

    public static void main (String[] args){
        Skype s = null;
        try {
            s = Skype.login("*****", "****"); //Censored
            s.subscribe();
            System.out.println("Successfully logged in!");
            for(Chat c : s.getAllChats()){
                c.sendMessage(Message.fromHtml("<b>Siwabot è online!</b>"));
            }
        } catch (SkypeException | IOException e) {
            e.printStackTrace();
        }
        s.getEventDispatcher().registerListener(new Listener(){

            @EventHandler
            public void on(MessageReceivedEvent e) throws SkypeException{
                String mess = e.getMessage().getMessage().toString();

                String[] args = mess.split(" ");

                String command = args[0];

                if(command.equalsIgnoreCase("!check")){
                    if(args.length == 1){
                        e.getChat().sendMessage(Message.create().with(Text.plain("Devi scrivere il nick!")));
                    }else if(args.length == 2){
                        String nick = args[1];
                        try{
                            URL url = new URL("https://minecraft.net/haspaid.jsp?user=" + nick);
                            String isPremium = new BufferedReader(new InputStreamReader(url.openStream())).readLine().toUpperCase();
                            boolean premium = Boolean.valueOf(isPremium);
                            if(premium){
                                e.getChat().sendMessage(Message.create().with(Text.plain(nick + " ha una copia legale di minecraft!")));
                            }else{
                                e.getChat().sendMessage(Message.create().with(Text.plain(nick + " non ha una copia legale di minecraft!")));
                            }
                        }catch(Exception ex){
                            ex.printStackTrace();
                        }
                    }
                }else if(command.equalsIgnoreCase("!server")){
                    if(args.length == 1){
                        e.getChat().sendMessage(Message.create().with(Text.plain("Devi scrivere il nick!")));
                    }
                }

                System.out.println(e.getMessage().getMessage());

        }

    });     

  } 

}
```

**Comment by samczsun** [comment]
Make sure your username is all lowercase for now

**Comment by sistem21** [comment]
bot's username?Actually it has 2 uppercase: "SiwaBot" ( S & B)

**Comment by samczsun** [comment]
So log in as 'siwabot'
