### ISSUE TITLE
405 error while submitting a messaging service

### ISSUE THREAD

**Issue by vmarchaud** [samczsun/Skype4J#34]
log here : http://pastebin.com/7FEzPn1T
i added my self the "code : x" just to look which error it was.
I think they changed the api, can you just take a look ? Thanks :)

**Comment by ducc** [comment]
My bot seems to be working fine, mind providing some code so this can be reproduced?

**Comment by samczsun** [comment]
I believe Skype made a major update to their API which has rendered this API temporary nonfunctional.

I will look into it but help is always appreciated from anyone

**Comment by vmarchaud** [comment]
there is the code of my bot : http://pastebin.com/NJZneynW
(just the part before exception is thrown)

I will look to debug it, not soon cause i'm busy finding a flat but after i will.

**Comment by samczsun** [comment]
Never mind. It was a bug introduced by me. Will push a fix soon
