### ISSUE TITLE
Relies on file.encoding

### ISSUE THREAD

**Issue by dluciv** [samczsun/Skype4J#37]
Using `com.samczsun:skype4j:0.0.9-SNAPSHOT` version of Skype4J, Windows, Russian locale, file encoding is `windows-1251` (Russian Windows default).

When running with default settings, it considers UTF-8 strings as CP-1251 ones somewhere. It leads, for example, to appearannce of _СЃРєР°Р№Рї_ in place of _скайп_.

When running with `-Dfile.encoding=UTF-8`, everything is ok.

**Comment by samczsun** [comment]
Strange... Can you tell me where this misencoding occurs?

**Comment by dluciv** [comment]
After debugging more thoroughly with explicit `-Dfile.encoding=windows-1251` setting, discovered that it definitely happens when receiving message. Sending message is ok.

I havent debugged this to the bottom, but suspicious that the problem is in `/src/main/java/com/samczsun/skype4j/internal/StreamUtils.java`,

```
ByteArrayOutputStream out = new ByteArrayOutputStream();
...
return out.toString();
```

As http://docs.oracle.com/javase/7/docs/api/java/io/ByteArrayOutputStream.html#toString%28%29 says, it uses platform's default character set.

May be `toString(String charsetName)` with explicit UTF-8 can help.

**Comment by samczsun** [comment]
Oh shoot. Good sleuthing! I'll fix that up and try to make sure there aren't any more soon

**Comment by dluciv** [comment]
Good luck!

Your library is very important one, likely one of _only two_ third-party Skype HTTP libraries. The second I know is one from Pidgin plugin.

**Comment by ducc** [comment]
"only" https://github.com/Sponges/SkypeAPIs ;)

**Comment by samczsun** [comment]
Sorry, "most up to date"? What is that implying?

**Comment by ducc** [comment]
More features, frequently updated, incredibly stable in comparison to when I used Skype4J.
Feel free to PR with corrections, it's just a document to help others find Skype APIs.

**Comment by dluciv** [comment]
And both Skype4J and EzSkype fail with `Server returned HTTP response code: 403 for URL: https://db3-client-s.gateway.messenger.live.com/v1/users/ME/endpoints` now.

Skype is ICQ of present =)

**Comment by samczsun** [comment]
Still works for me. Please post the full stacktrace and the code you are using

**Comment by dluciv** [comment]
Just tiny logging in code. May be my local issue (two libraries at the same time...), please just ignore it.
I will post a bug when I consider it reproducible.

**Comment by dluciv** [comment]
Sorry, it was not related to this particular issue =). It is an offtopic.
