### ISSUE TITLE
please give example of code

### ISSUE THREAD

**Issue by vinnitu** [samczsun/Skype4J#39]
404 here = https://gist.github.com/SpongyBacon/b6beb3f7f67d071e897e
Show please example with send/accept contact request

Thx

**Comment by samczsun** [comment]
404 Not Found

**Comment by vinnitu** [comment]
I see 404 too ) But where is gist?

**Comment by samczsun** [comment]
Ah, I see. I'll update the wiki with a new example soon

**Comment by ctian1** [comment]
There's a new example now
