### ISSUE TITLE
is it possible to send contact request to other client with this library?

### ISSUE THREAD

**Issue by vinnitu** [samczsun/Skype4J#40]
can you give me snippet of code?

**Comment by samczsun** [comment]
It is not possible yet

**Comment by ctian1** [comment]
This should be closed with one of the recent commits, right?

**Comment by samczsun** [comment]
Contact#sendRequest()
Contact#authorize()
Contact#unauthorize()
Contact#block()
Contact#unblock()

**Comment by ducc** [comment]
Tiny tweak, but maybe change #authorize to #accept and #unauthorize to #decline to make it clearer that it accepts or declines the contact?

**Comment by samczsun** [comment]
It doesn't make sense to 'decline' a contact whom you've already authorized

**Comment by ducc** [comment]
Ah, so it's the same request when deleting a contact then?

**Comment by samczsun** [comment]
Yes
