### ISSUE TITLE
Feature: Accepting skype contacts

### ISSUE THREAD

**Issue by ducc** [samczsun/Skype4J#5]
Is there a way to do this? I know you had a way to mass accept on coeus ;)

**Comment by samczsun** [comment]
Skype Web uses websockets to notify the client of new contact requests. I haven't had the time to look at the implementation for that yet. It strikes me odd though considering they have a perfectly good HTTP long poll system already that they would use something completely different for contacts

**Comment by ducc** [comment]
Yeah, doesn't surprise me though. It is Skype after all...

**Comment by Evoltr** [comment]
![fantaboy](https://cloud.githubusercontent.com/assets/8143868/8768210/ffadd9b4-2e77-11e5-8c74-54d42bc5db7d.jpg)

**Comment by Evoltr** [comment]
@samczsun is a scrub

**Comment by SpongyBacon** [comment]
@Evoltr is #1 kekker
