### ISSUE TITLE
Events not triggered...

### ISSUE THREAD

**Issue by yar229** [samczsun/Skype4J#51]
After 5-6 hours online (maybe after internet failure on a second) Skype4j does not receive messages, and I see no exceptions, events, everything is clear...
Any suggestions?
Thanks.

**Comment by samczsun** [comment]
Please try listening to MajorErrorEvent and MinorErrorEvent to see if something has gone wrong during parsing of events

**Comment by yar229** [comment]
Has monitored them for 3 days, no MajorErrorEvent, no MinorErrorEvent. 
And still no MessageReceivedEvent after 6..12 hours :(

**Comment by DarkSeraphim** [comment]
What version are you on? And what code is used to come to the conclusion you aren't receiving messages?

**Comment by samczsun** [comment]
Wait, you've kept the API running for over 3 days? It's not stable after 24 hours (something I'm working on) and events could stop working entirely

**Comment by ducc** [comment]
"It's not stable after 24 hours"
Psst temporary fix is to relog every 24 hours and swap the instance ;)

**Comment by yar229** [comment]
Yep, so what I do
