### ISSUE TITLE
Private Chat vs Group Chat

### ISSUE THREAD

**Issue by ThisGrizz** [samczsun/Skype4J#52]
Message Received Event is not fired when my account receives a message in a private chat but works in group chats. Please add support for private messaging if you can.

P.S. I would also like if on the Topic Update Event it would be possible to get the old topic. If that is not possible, sorry to ask. But if it is, thanks in advance.

**Comment by DarkSeraphim** [comment]
Private chat worked for me on the latest build... Can you post the source code used to verify that it did not work?

As for the TopicUpdateEvent, the Chat object passed to the event instance still uses the old topic, which you can get with `((GroupChat)event.getChat()).getTopic()`.

**Comment by samczsun** [comment]
I will add a getOldTopic function.

**Comment by ThisGrizz** [comment]
The Private Chat and Group Chat just randomly fixed itself. Thanks for the old topic function anyways <3
