### ISSUE TITLE
Severe Error

### ISSUE THREAD

**Issue by ThisGrizz** [samczsun/Skype4J#53]
I received some messages and was told to open a ticket and send them.

Here are the messages:
http://hastebin.com/raw/pugukoxali

They were accompanied by:
SEVERE: CONTROL_LIVE_STATE is in need of implementation! Please open a ticket with the following JSON data
Dec 05, 2015 1:00:10 PM com.samczsun.skype4j.internal.MessageType$23 handle

**Comment by samczsun** [comment]
I have removed this notification in the latest build after discovering that CONTROL_LIVE_STATE is used for calling (something I don't plan on supporting in the near future). You can feel free to ignore the warnings (although they do tend to spam a bit once a call is made)
