### ISSUE TITLE
Edit: not needed 

### ISSUE THREAD

**Issue by NotGGhost** [samczsun/Skype4J#68]
[redacted]

**Comment by NotGGhost** [comment]
Live SOAP request:
https://login.live.com/RST2.srf
http://hastebin.com/tojuzejoge.xml
POST/application/json

(Stripped from Tridan Client ("Ghost Client"), which uses MSNP over RESTFUL, but that should be the right wsa address)

**Comment by NotGGhost** [comment]
Captchaless login (less hacky)

POST: https://api.skype.com/login/skypetoken
DATA: scopes=client&clientVersion=0%2F7.17.0.105%2F%2F&username=itsgghost&passwordHash={REDACTED}

Hash = the classic "username\nskyper\npassword" base64 encoded MD5 BINARY

**Comment by samczsun** [comment]
:+1: I will try to implement these after midterms. Thank you for the help!

**Comment by NotGGhost** [comment]
Might be worth noting when converting the md5 to base64, it must be in a binary form and not an ascii string.
