### ISSUE TITLE
Get group chat

### ISSUE THREAD

**Issue by suxarik** [samczsun/Skype4J#70]
Hello. How can I get already created group chat, in order to send a message there? Even if I save that chat in my contacts I can't seem able to get it form GetAllChats() or allContacts

**Comment by samczsun** [comment]
See #66. Alternatively, use loadChat("19:someidhere@thread.skype")

**Comment by suxarik** [comment]
I've tried and it worked with new chats, but how about old chats with naming still "#name1/$name2;d76f78d687d" ? This one won't load
