### ISSUE TITLE
UnsupportedOperationException while login

### ISSUE THREAD

**Issue by pikkvile** [samczsun/Skype4J#71]
java.lang.UnsupportedOperationException: Not a string: 81028

The following code causes UOE:

```
Skype skype = new SkypeBuilder("login", "pass").withAllResources().build();
skype.login();
```

This happens within FullClient::registerWebSocket method, theese lines:

```
Map<String, String> data = new HashMap<>();
            for (JsonObject.Member value : policyResponse) {
                data.put(value.getName(), value.getValue().asString());
            }
```

This is because one of the properties inside policyResponce is JsonNumber and can not be got asString.

**Comment by NotGGhost** [comment]
Websockets aren't required for anything really apart from tracking... You should be safely be able to remove that and/or extend the websocket super class and ignore the send payload functions

**Comment by samczsun** [comment]
Websocket are used for live contact notifications, and so are medium priority. With the latest code the api should not disable if websockets fail but it looks like I have missed something.

**Comment by NotGGhost** [comment]
Are they? Haven't looked at them in a while, and as for contacts, the poller -should- was handling that.

**Comment by samczsun** [comment]
@pikkvile This has been fixed already. Just hasn't been pushed to Maven Central yet

**Comment by pikkvile** [comment]
Yes, I cloned the repo and saw latest changes. Do you plan to release 0.1.5 in Maven Central?

**Comment by samczsun** [comment]
Yes, but the current build is contains some bugs not fit for release, so that's why there is a delay
