### ISSUE TITLE
Sometimes logout() throws IllegalStateException, even when no previous shutdown request is submitted

### ISSUE THREAD

**Issue by vemacs** [samczsun/Skype4J#74]
```
04:16:15 [SEVERE] java.lang.IllegalStateException: API is shut down
04:16:15 [SEVERE]     at com.samczsun.skype4j.internal.Endpoints.open(Endpoints.java:172)
04:16:15 [SEVERE]     at com.samczsun.skype4j.internal.client.FullClient.logout(FullClient.java:91)
04:16:15 [SEVERE]     at dank.memes.skype.SkypeBot.lambda$loadSkype$1(SkypeBot.java:195)
04:16:15 [SEVERE]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
04:16:15 [SEVERE]     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
04:16:15 [SEVERE]     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
04:16:15 [SEVERE]     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
04:16:15 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
04:16:15 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
04:16:15 [SEVERE]     at java.lang.Thread.run(Thread.java:745)
```

This happens very inconsistently on a periodic relog task every 90 minutes, about 1/10th of the time. It doesn't seem to cause any issues, but I am curious as to why it's happening.

**Comment by samczsun** [comment]
It means that an internal error occured and in order to prevent your Skype account from being locked, the api has disabled itself to prevent malformed requests. Try adding an errorhandler to catch those errors and be notified when the api will be shut down.

Also, the api can currently stay online for about 28 hours. I'm working out the bugs that cause it to break at the 28 hour mark

**Comment by vemacs** [comment]
Any possibility of changing ErrorHandler to an interface? Can't use lambdas with abstract classes.

**Comment by vasiliicuhar** [comment]
Same issue. Source is: https://github.com/samczsun/Skype4J/blob/master/src/main/java/com/samczsun/skype4j/internal/threads/KeepaliveThread.java#L42

ping endpoint returns 500 Internal Server Error
Can we fix this in some way?
