### ISSUE TITLE
Exception while handling message

### ISSUE THREAD

**Issue by sistem21** [samczsun/Skype4J#84]
Hello and sorry for trouble, @samczsun 
Every 30 seconds i get this error in console: 

mar 27, 2016 2:16:06 PM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
GRAVE: Exception while handling message
java.lang.NullPointerException
    at com.samczsun.skype4j.internal.SkypeImpl$1$1.run(SkypeImpl.java:106)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

mar 27, 2016 2:16:06 PM com.samczsun.skype4j.internal.SkypeImpl$1$1 run
GRAVE: {}

Tell me if you need my code or other,and thanks in advance ;)

Sorry for my bad english ;)

**Comment by samczsun** [comment]
Please try running with the latest build. You can do that using jitpack.io or locally installing the latest commit. The current line number makes no sense.

**Comment by sistem21** [comment]
Ok thanks i've fixed it,but i'm very new to the latest version so can you tell me how i can parse a message?
I've tried in multiple ways but it never returns me the message as a string,i also tried to print it but it always print me it such as a normal object,thanks in advance, @samczsun ;)

**Comment by sistem21** [comment]
Thank you!
