### ISSUE TITLE
Log in failure

### ISSUE THREAD

**Issue by orimay** [samczsun/Skype4J#88]
Can not log in. Credentials are fine, checked on regular Skype client. Here is what I keep getting:

```
Message: While logging in (400 Bad Request)
ResponseCode: 400
ResponseMessage: Bad Request
StackTrace:
```

`com.samczsun.skype4j.exceptions.ConnectionException: While logging in (400 Bad Request) at com.samczsun.skype4j.internal.ExceptionHandler.generateException(ExceptionHandler.java:50) at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:372) at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:302) at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.post(Endpoints.java:282) at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:70) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at coldfusion.runtime.StructBean.invoke(StructBean.java:508) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3159) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3066) at cfSkypeClient2ecfc502157160$funcINIT.runFunction(D:\ACDDProjects\ACDD\trunk\src\Lighthouse\components\skype\SkypeClient.cfc:22) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492) at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:439) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:409) at coldfusion.runtime.CFPage.___createObjectInternal(CFPage.java:11629) at coldfusion.runtime.CFPage._createObject(CFPage.java:11596) at cfskypebot2ecfm681899910.runPage(D:\ACDDProjects\ACDD\trunk\src\lighthouse\scheduled\hourly\skypebot.cfm:54) at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:251) at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736) at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572) at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) at coldfusion.filter.IpFilter.invoke(IpFilter.java:45) at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:479) at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43) at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) at coldfusion.filter.PathFilter.invoke(PathFilter.java:142) at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30) at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94) at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60) at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) at coldfusion.CfmServlet.service(CfmServlet.java:219) at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121) at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:532) at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:874) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745)`

**Comment by ctian1** [comment]
Are you using the latest version of Skype4J?

**Comment by vemacs** [comment]
Yes. This is only an issue with recent versions of Skype4j, it does not occur with 0.1.5-SNAPSHOT.

```
22:49:05 [SEVERE] com.samczsun.skype4j.exceptions.ConnectionException: While subscribing (400 Bad Request)
22:49:05 [SEVERE]     at com.samczsun.skype4j.internal.ExceptionHandler.generateException(ExceptionHandler.java:50)
22:49:05 [SEVERE]     at com.samczsun.skype4j.internal.SkypeImpl.subscribe(SkypeImpl.java:457)
22:49:05 [SEVERE]     at dank.memes.skype.SkypeBot.loadSkype(SkypeBot.java:180)
22:49:05 [SEVERE]     at dank.memes.skype.SkypeBot.start(SkypeBot.java:82)
22:49:05 [SEVERE]     at dank.memes.skype.MrSkeltalBootstrap.main(MrSkeltalBootstrap.java:12)
```

**Comment by samczsun** [comment]
Will take a look tomorrow

**Comment by orimay** [comment]
Yup, compiled the lastest

**Comment by orimay** [comment]
If that helps, a couple months ago it was working just fine, and this time the same compilation started failing with this error. Maybe Microsoft changed something on their side?

**Comment by samczsun** [comment]
I wasn't able to reproduce it last time. I can try again but without knowing more details like you username and password (which is what is posted to that particular endpoint) there's not much testing I can do

**Comment by camdenorrb** [comment]
Can confirm, it has happened when I tried on a different skype account.
Might be due to capitals in skype username.

**Comment by Orimay** [comment]
Username: lighthouse.pro
Password: TestPassword

**Comment by samczsun** [comment]
I'll be able to debug in an hour or so. If you like drop me an email at skype4j.88@samczsun.com with a different password ;)

**Comment by samczsun** [comment]
Yep, definitely noticing the login issue now. Is that a Skype account or a Microsoft account?

**Comment by samczsun** [comment]
@Orimay So I tried it using the command line and I got this as the response:

```
{
  "status": {
    "code": 40121,
    "text": "Too many failed authentication attempts with given username or IP."
  }
}
```
