### ISSUE TITLE
nullclient-s.gateway.messenger.live.com

### ISSUE THREAD

**Issue by yar229** [samczsun/Skype4J#9]
```
        _skype = new SkypeImpl(Settings.Default.SkypeLogin, Settings.Default.SkypePassword);
        _skype.login();
        var dispatcherv = _skype.getEventDispatcher();
        dispatcherv.registerListener(new MessageListener(OnSkypeMessage));
        _skype.subscribe();
```

and then I got

Exception:Thrown: "nullclient-s.gateway.messenger.live.com" (java.net.UnknownHostException)
A java.net.UnknownHostException was thrown: "nullclient-s.gateway.messenger.live.com"

**Comment by yar229** [comment]
Imho, it's not right to just initialize cloud as blank...

``` java
private HttpURLConnection registerEndpoint(String skypeToken)
...
            HttpURLConnection connection = builder.build(); 
            int code = connection.getResponseCode();
            /* ------> need to be here ---->>> */ 
            updateCloud(connection.getHeaderField("Location"));

            if (code >= 301 && code <= 303 || code == 307) {
...
```

**Comment by samczsun** [comment]
If you are not in any cloud, then your cloud would be blank and that code would never be called. If you are in a cloud, then your blank cloud would be overwritten with your current one. I'm not sure what you mean?

**Comment by yar229** [comment]
Yep, thank you, I've caught it now
