### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by orimay** [samczsun/Skype4J#90]
`While logging in Response: 401 Unauthorized Begin Message {"status":{"code":40120,"text":"Authentication failed. Bad username or password."}} End message`

Keep getting authentication failure with the most recent build. Regular skype client accepts credentials.
Username: lighthouse.pro
Password: TestPassword

**Comment by samczsun** [comment]
Works fine for me. Check if you're supplying the right username and password

**Comment by orimay** [comment]
This exact credentials provide me same error. I use this library from within ColdFusion.

**Comment by samczsun** [comment]
How are you using the credentials? Is it hard coded? While testing I thought it wasn't working but I was just reading extra data from my credentials file which was appended onto the password. Once I fixed that I logged in just fine.

**Comment by orimay** [comment]
Wow! My bad, sorry. I had an additional argument on my arguments list. Thank You very much!

**Comment by samczsun** [comment]
No problem
