### ISSUE TITLE
Can't edit message in a group chat.

### ISSUE THREAD

**Issue by camdenorrb** [samczsun/Skype4J#95]
`
         try {
                    SentMessage message1 = (SentMessage) chat.sendMessage(Message.create().with(Text.plain("Kat")));

```
                    try {Thread.sleep(6000);
                        message1.edit(Message.create().with(Text.NEW_LINE));

                    }catch (Exception ex) {ex.printStackTrace();}
```

 } catch (Exception e) {e.printStackTrace();}
`

Error whilst in group chat (Works in private chat)

`java.lang.ClassCastException: com.samczsun.skype4j.internal.chat.messages.ReceivedMessageImpl cannot be cast to com.samczsun.skype4j.chat.messages.SentMessage
`

**Comment by ctian1** [comment]
Are you on the latest version? Also, full stack trace?

**Comment by ducc** [comment]
@camdenorrb did you fix this?

**Comment by camdenorrb** [comment]
Haven't used Skype4j for a while, I will try it out hold on.

**Comment by camdenorrb** [comment]
Appears to be fixed, :3.
